apiVersion: skaffold/v4beta9
kind: Config

build:
  local:
    push: false
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: mohammedrisvanvm/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mohammedrisvanvm/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mohammedrisvanvm/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mohammedrisvanvm/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mohammedrisvanvm/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mohammedrisvanvm/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.*"
            dest: .

deploy:
  helm:
    releases:
      - name: ticketing
        chartPath: infra/ticketing   # ✅ Correct path to your helm chart
        wait: true
        skipBuildDependencies: true
        setValues:
          auth.image.repository: mohammedrisvanvm/auth
          tickets.image.repository: mohammedrisvanvm/tickets
          orders.image.repository: mohammedrisvanvm/orders
          expiration.image.repository: mohammedrisvanvm/expiration
          payments.image.repository: mohammedrisvanvm/payments
          frontend.image.repository: mohammedrisvanvm/frontend
