apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-expiration-redis
  labels:
    app: expiration-redis
    {{- include "ticketing.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
        {{- include "ticketing.labels" . | nindent 8 }}
    spec:
      containers:
        - name: expiration-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379

          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 20

          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-expiration-redis-srv
spec:
  selector:
    app: expiration-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
