apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.22.0
          args:
            - "--cluster_id=ticketing"
            - "--store=memory"
            - "--cluster_log_path=/data"
          ports:
            - containerPort: 4222
              name: client
          resources:
      {{- toYaml .Values.nats.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
