apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-orders
  labels:
    app: orders
    {{- include "ticketing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
        {{- include "ticketing.labels" . | nindent 8 }}
    spec:
      containers:
        - name: orders
          image: "{{ .Values.orders.image.repository }}:{{ .Values.orders.image.tag }}"
          env:
            - name: NATS_URL
              value: nats://{{ include "ticketing.fullname" . }}-nats-srv:4222

            - name: NATS_CLUSTER_ID
              value: ticketing

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: MONGO_URI
              value: mongodb://{{ include "ticketing.fullname" . }}-orders-mongo-srv:27017/orders

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 3000
      targetPort: 3000
