apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-payments-mongo
  labels:
    app: payments-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongo
  template:
    metadata:
      labels:
        app: payments-mongo
    spec:
      containers:
        - name: payments-mongo
          image: mongo
          ports:
            - containerPort: 27017
      resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-payments-mongo-srv
spec:
  selector:
    app: payments-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
