apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing.fullname" . }}-tickets
  labels:
    app: tickets
    {{- include "ticketing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tickets.replicaCount }}
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
        {{- include "ticketing.labels" . | nindent 8 }}
    spec:
      containers:
        - name: tickets
          image: "{{ .Values.tickets.image.repository }}:{{ .Values.tickets.image.tag }}"
          env:
            - name: NATS_URL
              value: nats://{{ include "ticketing.fullname" . }}-nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://{{ include "ticketing.fullname" . }}-tickets-mongo-srv:27017/tickets
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
      resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing.fullname" . }}-tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: http
      port: 3000
      targetPort: 3000
